# Generated by Django 3.1.2 on 2021-01-22 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210122_1604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name_plural': 'Users Profiles'},
        ),
    ]
