# Generated by Django 3.1.2 on 2021-01-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20210122_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='receiving_newsletter',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
