# Generated by Django 3.1.2 on 2021-01-24 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_userprofile_email_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='receiving_newsletter',
        ),
    ]
