# Generated by Django 3.1.2 on 2021-01-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_userprofile_receiving_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='receiving_newsletter',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3),
        ),
    ]
