# Generated by Django 3.1.2 on 2021-01-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_auto_20210124_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='receiving_newsletter',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
    ]
