# Generated by Django 3.1.2 on 2020-11-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('age', models.CharField(max_length=2)),
                ('about', models.TextField(max_length=1024)),
                ('riding_style', models.CharField(max_length=100)),
                ('favourite_trick', models.TextField(max_length=100)),
                ('qualifications', models.CharField(max_length=254)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Instructors Profiles',
            },
        ),
    ]
