# Generated by Django 3.1.2 on 2021-01-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorprofile',
            name='about',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='instructorprofile',
            name='age',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
