# Generated by Django 3.1.2 on 2020-11-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructorprofile',
            name='favourite_trick',
        ),
        migrations.RemoveField(
            model_name='instructorprofile',
            name='riding_style',
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='style',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='trick',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instructorprofile',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instructorprofile',
            name='age',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='instructorprofile',
            name='qualifications',
            field=models.TextField(blank=True, null=True),
        ),
    ]
