# Generated by Django 3.1.2 on 2020-11-27 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20201126_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructorprofile',
            name='qualifications',
        ),
        migrations.RemoveField(
            model_name='instructorprofile',
            name='style',
        ),
        migrations.RemoveField(
            model_name='instructorprofile',
            name='trick',
        ),
    ]
