# Generated by Django 3.1.2 on 2020-11-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20201127_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructorprofile',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='instructorprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='instructors'),
        ),
    ]
