# Generated by Django 3.1.2 on 2021-01-02 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quote',
            new_name='QuoteText',
        ),
    ]
