# Generated by Django 3.1.2 on 2021-01-24 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20210102_2103'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuoteText',
        ),
    ]
