# Generated by Django 3.1.2 on 2020-11-26 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='levels',
            options={'verbose_name_plural': 'Level'},
        ),
    ]
