# Generated by Django 3.1.2 on 2021-01-27 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialicon',
            name='title',
        ),
        migrations.AddField(
            model_name='socialicon',
            name='name',
            field=models.TextField(choices=[('facebook', 'Facebook'), ('youtube', 'Youtube'), ('pinterest', 'Pintereset'), ('snapchat', 'Snapchat'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('tiktok', 'Tiktok'), ('viemo', 'Vimeo')], default='Facebook', max_length=40),
        ),
    ]
