# Generated by Django 3.1.2 on 2020-12-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialicon',
            name='url',
            field=models.URLField(blank=True, default=' ', max_length=1024, null=True),
        ),
    ]
