# Generated by Django 3.1.2 on 2020-11-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201125_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='url',
            field=models.URLField(blank=True, default='#', max_length=1024, null=True),
        ),
    ]
