# Generated by Django 3.1.2 on 2020-12-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201212_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialicon',
            name='url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
