# Generated by Django 3.1.2 on 2021-01-29 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210127_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialicon',
            name='icon',
            field=models.CharField(choices=[('fa-facebook-f', 'Facebook'), ('fa-youtube', 'Youtube'), ('fa-pinterest-p', 'Pintereset'), ('fa-snapchat-ghost', 'Snapchat'), ('fa-twitter', 'Twitter'), ('fa-instagram', 'Instagram'), ('fa-tiktok', 'Tiktok'), ('fa-vimeo-v', 'Vimeo')], max_length=30),
        ),
        migrations.AlterField(
            model_name='socialicon',
            name='name',
            field=models.TextField(choices=[('facebook', 'Facebook'), ('youtube', 'Youtube'), ('pinterest', 'Pintereset'), ('snapchat', 'Snapchat'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('tiktok', 'Tiktok'), ('vimeo', 'Vimeo')], default='Facebook', max_length=40),
        ),
    ]
