# Generated by Django 3.1.2 on 2021-01-30 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210129_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessoncard',
            name='description',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='levelcard',
            name='description',
            field=models.TextField(max_length=300),
        ),
    ]
