# Generated by Django 3.1.2 on 2020-11-29 18:58

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Resort Name', max_length=120)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('street_address', models.CharField(max_length=80)),
                ('about', models.TextField(default='Some text about resort')),
                ('levels', models.TextField(default='Type levels as example: Beginner, Intermediate, Advance, etc.')),
                ('styles', models.TextField(default='Type styles as example: Freestyle Riding, Carving, Off-Psite, etc.')),
                ('instructors', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='resorts')),
            ],
        ),
    ]
