# Generated by Django 3.1.2 on 2020-12-13 13:17

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('about', models.TextField()),
                ('open_season', models.CharField(default='December - April', max_length=120)),
                ('top_altitude', models.IntegerField(default=0)),
                ('bottom_altitude', models.IntegerField(default=0)),
                ('resort_altitude', models.IntegerField(default=0)),
                ('levels', models.TextField()),
                ('instructors', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='resorts')),
            ],
        ),
    ]
