# Generated by Django 3.1.2 on 2020-11-30 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resort',
            name='street_address',
        ),
    ]
