# Generated by Django 3.1.2 on 2020-11-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0002_auto_20201129_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resort',
            name='about',
            field=models.TextField(default='Some text about resort'),
        ),
    ]
