# Generated by Django 3.1.2 on 2020-11-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0003_auto_20201129_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resort',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='resort',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='resorts'),
        ),
    ]
