# Generated by Django 3.1.2 on 2020-11-29 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0004_auto_20201129_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resort',
            old_name='address',
            new_name='street_address',
        ),
        migrations.RemoveField(
            model_name='resort',
            name='map_link',
        ),
    ]
