# Generated by Django 3.1.2 on 2020-12-16 21:21

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0004_auto_20201216_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resort',
            name='country',
            field=django_countries.fields.CountryField(max_length=200),
        ),
    ]
