# Generated by Django 3.1.2 on 2020-12-16 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0005_auto_20201216_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resort',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='resort',
            name='open_season',
            field=models.CharField(default='December - April', max_length=120),
        ),
    ]
