# Generated by Django 3.1.2 on 2020-12-06 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='promo_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
