# Generated by Django 3.1.2 on 2020-12-14 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0001_initial'),
        ('home', '0001_initial'),
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lesson',
            new_name='LessonCard',
        ),
    ]
