# Generated by Django 3.1.2 on 2020-12-07 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0003_auto_20201130_2306'),
        ('lessons', '0003_lesson_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='place',
        ),
        migrations.AddField(
            model_name='lesson',
            name='resort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resorts.resort'),
        ),
    ]
