# Generated by Django 3.1.2 on 2020-12-07 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('resorts', '0003_auto_20201130_2306'),
        ('lessons', '0004_auto_20201207_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lessons.category'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.levelcard'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='resort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='resorts.resort'),
        ),
    ]
