# Generated by Django 3.1.2 on 2020-12-07 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_auto_20201207_1958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='display_order',
            new_name='order',
        ),
    ]
